#### WORKFLOW #####
# Name of the Workflow
name: CICD

# when does the workflow run
on: push

#### JOBS #####
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v7

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Code Build
        uses: docker/login-action@v4   #action

      - name: Setup
        run: echo "Builed"  #action
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Code test
        run: echo "Code test done"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Code Deploy
        run: echo "Code deploy done"
